import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import AgenticMonitoringPanel from './AgenticMonitoringPanel.jsx'
import {
  listAgenticApprovals,
  listAgenticProfiles,
  rescanAgenticProfile,
} from '../utils/agenticApi.js'

vi.mock('../utils/agenticApi.js', () => ({
  approveAgenticApproval: vi.fn(),
  listAgenticApprovals: vi.fn(),
  listAgenticProfiles: vi.fn(),
  rejectAgenticApproval: vi.fn(),
  rescanAgenticProfile: vi.fn(),
}))

const RESULT = {
  slug: 'crest-example',
  canonicalProfile: {
    source: {
      sourceUrl: 'https://crest.example/services',
    },
    metadata: {
      updatedAt: '2026-04-29T20:00:00.000Z',
    },
  },
}

describe('AgenticMonitoringPanel', () => {
  beforeEach(() => {
    listAgenticProfiles.mockResolvedValue({
      profiles: [
        {
          slug: 'crest-example',
          version: 1,
          updatedAt: '2026-04-29T20:00:00.000Z',
          monitoring: {
            lastRescanStatus: 'not_scanned',
          },
        },
      ],
    })
    listAgenticApprovals.mockResolvedValue({ approvals: [] })
    rescanAgenticProfile.mockResolvedValue({
      status: 'approval_required',
      changed: true,
      changes: [
        {
          type: 'pricing_changed',
          path: 'claims[pricing]',
          approval_required: true,
        },
      ],
      feedback: {
        ruleBased: {
          status: 'approval_required',
          summary: '1 sensitive change(s) require approval before publishing.',
          recommendation: 'Review the pending approval details.',
          affectedArtifacts: ['hosted_profile', 'llms_full_txt'],
        },
        llm: {
          status: 'ok',
          model: 'Qwen 3.6 Plus',
          message: 'Pricing changed, so verify the new amount before publishing the updated AI profile.',
        },
        message: '1 sensitive change(s) require approval before publishing.\n\nPricing changed, so verify the new amount before publishing the updated AI profile.',
      },
    })
  })

  it('renders combined rule-based and LLM rescan feedback', async () => {
    render(<AgenticMonitoringPanel result={RESULT} />)

    fireEvent.change(screen.getByLabelText(/updated markdown for rescan/i), {
      target: { value: '# Updated content\n\nPricing starts at $99 per month.' },
    })
    fireEvent.click(screen.getByRole('button', { name: /Rescan pasted content/i }))

    await screen.findByText(/Pricing changed, so verify the new amount/i)
    expect(screen.getByText(/1 sensitive change\(s\) require approval/i)).toBeInTheDocument()
    expect(screen.getByText(/Generated by Qwen 3.6 Plus/i)).toBeInTheDocument()
    await waitFor(() => {
      expect(rescanAgenticProfile).toHaveBeenCalledWith('crest-example', {
        markdown: '# Updated content\n\nPricing starts at $99 per month.',
      })
    })
  })
})
